#!/usr/bin/env python3

import argparse
import requests

def call_ml_service(command):
    try:
        url = 'http://localhost:11434/api/generate'
        payload = {
            "model": "llama3.1",
            "prompt": f"You are an terminal command helper. For the questions asked just give the command for it and nothing else. question: {command}"
        }
        response = requests.post(url, json=payload, stream=True)
        print(response)

        for line in response.iter_lines():
            if line:
                try:
                    json_response = requests.models.complexjson.loads(line.decode('utf-8'))
                    print(json_response["response"], end='')
                except ValueError as e:
                    print(f"Failed to parse JSON: {e}")
        return ''
    except Exception as e:
        return {"result": f"An error occurred: {str(e)}"}
    # except:
    #     return {"result": "error occured. check your internet connection. If it is fine, then shit has happened in the server :) I seriously hope you never get to see this message!!"}

def execute_command(command):
    print(command)
    ml_response = call_ml_service(command)
    print(ml_response)

def main():
    parser = argparse.ArgumentParser(description='ML-enhanced Command Line Tool')
    parser.add_argument('command', nargs='+', help='Command to execute')

    args = parser.parse_args()
    execute_command(' '.join(args.command))

if __name__ == "__main__":
    main()